// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wayther.Infrastructure;

#nullable disable

namespace Wayther.Infrastructure.Migrations
{
    [DbContext(typeof(WaytherDbContext))]
    [Migration("20260707162533_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Wayther.Infrastructure.ForecastCache", b =>
                {
                    b.Property<double>("Lat4")
                        .HasColumnType("double precision")
                        .HasColumnName("lat4");

                    b.Property<double>("Lon4")
                        .HasColumnType("double precision")
                        .HasColumnName("lon4");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.HasKey("Lat4", "Lon4");

                    b.ToTable("forecast_cache", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
